CREATE TABLE SV_CUSTOMER(
    ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(20),
    BIRTH_DATE DATE,
    PHONE_NUMBER VARCHAR2(10),
    ADDRESS VARCHAR2(100)
);

CREATE TABLE SV_TICKET(
    ID NUMBER PRIMARY KEY,
    OBJECT VARCHAR2(200),
    DESCRIPTION VARCHAR2(4000),
    FURTHER_INFORMATIONS VARCHAR2(999),
    DOCUMENTATION BLOB,
    CREATION_DATE TIMESTAMP,
    STATE VARCHAR2(50),
    PRIORITY VARCHAR2(50),
    VERSION NUMBER,
    CUSTOMER NUMBER REFERENCES SV_CUSTOMER(ID)
);

CREATE TABLE SV_OPERATOR(
    ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(20),
    BIRTH_DATE DATE,
    PHONE_NUMBER VARCHAR2(10),
    ADDRESS VARCHAR2(100),
    AUTHORIZATION_LEVEL VARCHAR2(50)
);

CREATE TABLE SV_ASSIGNMENT(
    ID NUMBER PRIMARY KEY,
    OPERATION_DATE TIMESTAMP,
    TICKET NUMBER REFERENCES SV_TICKET(ID),
    OPERATOR NUMBER REFERENCES SV_OPERATOR(ID)
);

CREATE TABLE  SV_COMMUNICATION(
    ID NUMBER PRIMARY KEY,
    OBJECT VARCHAR2(200),
    BODY VARCHAR2(4000),
    SEND_DATE TIMESTAMP,
    TICKET NUMBER REFERENCES SV_TICKET(ID),
    CUSTOMER NUMBER REFERENCES SV_CUSTOMER(ID),
    OPERATOR NUMBER REFERENCES SV_OPERATOR(ID)
);
